export const codigosPermisosInternos = [
    'proyectos.crear_proyecto',
    'proyectos.eliminar_proyecto',
    'proyectos.actualizar_proyecto',
    'proyectos.archivar_proyecto',
    'proyectos.cambiar_estado_proyecto',
    'proyectos.listar_proyectos',
    'proyectos.iniciar_proyecto',
    'proyectos.crear_tipo_HU',
    'proyectos.borrar_tipo_HU',
    'proyectos.actualizar_tipo_HU',
    'proyectos.importar_roles_internos',
    'proyectos.agregar_participante',
    'proyectos.modificar_participante',
    'proyectos.borrar_participante',
    'proyectos.listar_participante',
    'proyectos.listar_roles_internos',
    'proyectos.crear_rol_interno',
    'proyectos.actualizar_rol_interno',
    'proyectos.borrar_rol_interno',
    'proyectos.importar_tipo_HU',
    'proyectos.modificar_columnas_tipo_HU',
    'proyectos.listar_historias_usuario',
    'proyectos.obtener_historia_usuario',
    'proyectos.crear_historia_usuario',
    'proyectos.actualizar_historia_usuario',
    'proyectos.borrar_historia_usuario',
    'proyectos.listar_sprint_proyecto',
    'proyectos.crear_sprint',
    'proyectos.obtener_sprint',
    'proyectos.borrar_sprint',
    'proyectos.actualizar_sprint',
    'proyectos.ver_equipo_sprint',
    'proyectos.agregar_miembro_sprint',
    'proyectos.modificar_miembro_sprint',
    'proyectos.borrar_miembro_sprint',
    'proyectos.borrar_historia_sprintbacklog',
    'proyectos.agregar_historia_sprintbacklog',

]

export const nombresPermisosInternos = [
    'Crear proyecto',
    'Eliminar proyecto',
    'Actualizar proyecto',
    'Archivar proyecto',
    'Cambiar estado proyecto',
    'Listar proyectos',
    'Iniciar proyecto',
    'Crear tipo historia de usuario',
    'Borrar tipo historia de usuario',
    'Actualizar tipo historia de usuario',
    'Importar roles internos',
    'Agregar participante',
    'Modificar participante',
    'Borrar participante',
    'Listar participante',
    'Listar roles internos',
    'Crear rol interno',
    'Actualizar rol interno',
    'Borrar rol interno',
    'Importar tipo HU',
    'Modificar columnas tipo HU',
    'Listar historias de usuario',
    'Obtener historias de usuarios',
    'Crear historias de usuarios',
    'Actualizar historias de usuarios',
    'Borrar historias de usuarios',
    'Listar Sprints',
    'Crear Sprint',
    'Obtener Sprint',
    'Borrar Sprint',
    'Actualizar Sprint',
    'Ver equipo del sprint',
    'Agregar miembro al equipo sprint',
    'Modificar miembro del equipo sprint',
    'Borrar miembro de equipo sprint',
    'Borrar historia de usuario al sprintbacklog',
    'Agregar historias de usuario al sprintbacklog',
]