export const codigosPermisosInternos = [
    'proyectos.crear_proyecto',
    'proyectos.eliminar_proyecto',
    'proyectos.actualizar_proyecto',
    'proyectos.archivar_proyecto',
    'proyectos.cambiar_estado_proyecto',
    'proyectos.listar_proyectos',
    'proyectos.iniciar_proyecto',
    'proyectos.crear_tipo_HU',
    'proyectos.borrar_tipo_HU',
    'proyectos.importar_roles_internos',
    'proyectos.agregar_participante',
    'proyectos.modificar_participante',
    'proyectos.borrar_participante',
    'proyectos.listar_participante',
    'proyectos.listar_roles_internos',
    'proyectos.crear_rol_interno',
    'proyectos.actualizar_rol_interno',
    'proyectos.borrar_rol_interno',
]

export const nombresPermisosInternos = [
    'Crear proyecto',
    'Eliminar proyecto',
    'Actualizar proyecto',
    'Archivar proyecto',
    'Cambiar estado proyecto',
    'Listar proyectos',
    'Iniciar proyecto',
    'Crear tipo historia de usuario',
    'Borrar tipo historia de usuario',
    'Importar roles internos',
    'Agregar participante',
    'Modificar participante',
    'Borrar participante',
    'Listar participante',
    'Listar roles internos',
    'Crear rol interno',
    'Actualizar rol interno',
    'Borrar rol interno',
]